export const FETCH_SCORES_START = 'FETCH_SCORES_START';
export const FETCH_SCORES_SUCCESS = 'FETCH_SCORES_SUCCESS';
export const FETCH_SCORES_FAIL = 'FETCH_SCORES_FAIL';

export const POST_SCORE_START = 'POST_SCORE_START';
export const POST_SCORE_SUCCESS = 'POST_SCORE_SUCCESS';
export const POST_SCORE_FAIL = 'POST_SCORE_FAIL';